export const currencies = [
    {code:'AED(د.إ.)', name:'United Arab Emirates Dirham'},
    {code:'AFN(؋)', name:'Afghan Afghani'},
    {code:'ALL(Lek)', name:'Albanian Lek'},
    {code:'AMD(֏)', name:'Armenian Dram'},
    {code:'ANG(ƒ)', name:'Netherlands Antillean Guilder'},
    {code:'AOA(Kz)', name:'Angolan Kwanza'},
    {code:'ARS($)', name:'Argentine Peso'},
    {code:'AUD($)', name:'Australian Dollar'},
    {code:'AWG(ƒ)', name:'Aruban Guilder'},
    {code:'AZN(₼)', name:'Azerbaijani Manat'},
    {code:'BAM(KM)', name:'Bosnia and Herzegovina Convertible Mark'},
    {code:'BBD($)', name:'Barbadian Dollar'},
    {code:'BDT(৳)', name:'Bangladeshi Taka'},
    {code:'BGN(лв)', name:'Bulgarian Lev'},
    {code:'BHD(فلس)', name:'Bahraini Dinar'},
    {code:'BIF(FBu)', name:'Burundian Franc'},
    {code:'BMD($)', name:'Bermudian Dollar'},
    {code:'BND($)', name:'Brunei Dollar'},
    {code:'BOB($b)', name:'Bolivian Boliviano'},
    {code:'BRL(R$)', name:'Brazilian Real'},
    {code:'BSD($)', name:'Bahamian Dollar'},
    {code:'BTN(Nu)', name:'Bhutanese Ngultrum'},
    {code:'BWP(P)', name:'Botswana Pula'},
    {code:'BYN(Br)', name:'Belarusian Ruble'},
    {code:'BZD(BZ$)', name:'Belize Dollar'},
    {code:'CAD($)', name:'Canadian Dollar'},
    {code:'CDF(FC)', name:'Congolese Franc'},
    {code:'CHF(CHF)', name:'Swiss Franc'},
    {code:'CLP($)', name:'Chilean Peso'},
    {code:'CNY(¥)', name:'Chinese Yuan'},
    {code:'COP($)', name:'Colombian Peso'},
    {code:'CRC(₡)', name:'Costa Rican Colón'},
    {code:'CUC(CUC$)', name:'Cuban Convertible Peso'},
    {code:'CUP(₱)', name:'Cuban Peso'},
    {code:'CVE($)', name:'Cape Verdean Escudo'},
    {code:'CZK(Kč)', name:'Czech Koruna'},
    {code:'DJF(Fdj)', name:'Djiboutian Franc'},
    {code:'DKK(kr)', name:'Danish Krone'},
    {code:'DOP(RD$)', name:'Dominican Peso'},
    {code:'DZD(دج)', name:'Algerian Dinar'},
    {code:'EGP(£)', name:'Egyptian Pound'},
    {code:'ERN(Nfk)', name:'Eritrean Nakfa'},
    {code:'ETB(ብር))', name:'Ethiopian Birr'},
    {code:'EUR(€)', name:'Euro'},
    {code:'FJD($)', name:'Fijian Dollar'},
    {code:'FKP(£)', name:'Falkland Islands Pound'},
    {code:'GBP(£)', name:'British Pound'},
    {code:'GEL(₾)', name:'Georgian Lari'},
    {code:'GGP(£)', name:'Guernsey Pound'},
    {code:'GHS(¢)', name:'Ghanaian Cedi'},
    {code:'GIP(£)', name:'Gibraltar Pound'},
    {code:'GMD(GMD)', name:'Gambian Dalasi'},
    {code:'GNF(GFr)', name:'Guinean Franc'},
    {code:'GTQ(Q)', name:'Guatemalan Quetzal'},
    {code:'GYD($)', name:'Guyanese Dollar'},
    {code:'HKD($)', name:'Hong Kong Dollar'},
    {code:'HNL(L)', name:'Honduran Lempira'},
    {code:'HRK(kn)', name:'Croatian Kuna'},
    {code:'HTG(HTG)', name:'Haitian Gourde'},
    {code:'HUF(Ft)', name:'Hungarian Forint'},
    {code:'IDR(Rp)', name:'Indonesian Rupiah'},
    {code:'ILS(₪)', name:'Israeli New Shekel'},
    {code:'IMP(£)', name:'Manx Pound'},
    {code:'INR(₹)', name:'Indian Rupee'},
    {code:'IQD(ع.د)', name:'Iraqi Dinar'},
    {code:'IRR(﷼)', name:'Iranian Rial'},
    {code:'ISK(kr)', name:'Icelandic Króna'},
    {code:'JEP(£)', name:'Jersey Pound'},
    {code:'JMD(J$)', name:'Jamaican Dollar'},
    {code:'JOD(JD)', name:'Jordanian Dinar'},
    {code:'JPY(¥)', name:'Japanese Yen'},
    {code:'KES(KES)', name:'Kenyan Shilling'},
    {code:'KGS(лв)', name:'Kyrgyzstani Som'},
    {code:'KHR(៛)', name:'Cambodian Riel'},
    {code:'KID($)', name:'Kiribati Dollar'},
    {code:'KMF(KMF)', name:'Comorian Franc'},
    {code:'KPW(₩)', name:'North Korean Won'},
    {code:'KRW(₩)', name:'South Korean Won'},
    {code:'KWD(د.ك)', name:'Kuwaiti Dinar'},
    {code:'KYD($)', name:'Cayman Islands Dollar'},
    {code:'KZT(лв)', name:'Kazakhstani Tenge'},
    {code:'LAK(₭)', name:'Lao Kip'},
    {code:'LBP(£)', name:'Lebanese Pound'},
    {code:'LKR(Rs)', name:'Sri Lankan Rupee'},
    {code:'LRD($)', name:'Liberian Dollar'},
    {code:'LSL(LSL)', name:'Lesotho Loti'},
    {code:'LYD(ل.د)', name:'Libyan Dinar'},
    {code:'MAD(د.م.)', name:'Moroccan Dirham'},
    {code:'MDL(MDL)', name:'Moldovan Leu'},
    {code:'MGA(Ar)', name:'Malagasy Ariary'},
    {code:'MKD(ден)', name:'Macedonian Denar'},
    {code:'MMK(MMK)', name:'Burmese Kyat'},
    {code:'MNT(₮)', name:'Mongolian Tögrög'},
    {code:'MOP(MOP$)', name:'Macanese Pataca'},
    {code:'MRU(MRU)', name:'Mauritanian Ouguiya'},
    {code:'MUR(Rs)', name:'Mauritian Rupee'},
    {code:'MVR(ރ)', name:'Maldivian Rufiyaa'},
    {code:'MWK(MWK)', name:'Malawian Kwacha'},
    {code:'MXN($)', name:'Mexican Peso'},
    {code:'MYR(RM)', name:'Malaysian Ringgit'},
    {code:'MZN(MT)', name:'Mozambican Metical'},
    {code:'NAD($)', name:'Namibian Dollar'},
    {code:'NGN(₦)', name:'Nigerian Naira'},
    {code:'NIO(C$)', name:'Nicaraguan Córdoba'},
    {code:'NOK(kr)', name:'Norwegian Krone'},
    {code:'NPR(Rs)', name:'Nepalese Rupee'},
    {code:'NZD($)', name:'New Zealand Dollar'},
    {code:'OMR(﷼)', name:'Omani Rial'},
    {code:'PAB(B/.)', name:'Panamanian Balboa'},
    {code:'PEN(S/.)', name:'Peruvian Sol'},
    {code:'PGK(PGK)', name:'Papua New Guinean Kina'},
    {code:'PHP(₱)', name:'Philippine Peso'},
    {code:'PKR(Rs)', name:'Pakistani Rupee'},
    {code:'PLN(zł)', name:'Polish Złoty'},
    // {code:'PRB()', name:'Transnistrian Ruble'},
    {code:'PYG(Gs)', name:'Paraguayan Guaraní'},
    {code:'QAR(﷼)', name:'Qatari Riyal'},
    {code:'RON(lei)', name:'Romanian Leu'},
    {code:'RSD(Дин.)', name:'Serbian Dinar'},
    {code:'RUB(₽)', name:'Russian Ruble'},
    {code:'RWF(RWF)', name:'Rwandan Franc'},
    {code:'SAR(﷼)', name:'Saudi Riyal'},
    {code:'SBD($)', name:'Seychelles Rupees'},
    {code:'SCR(Rs)', name:'Seychelles Rupees'},
    {code:'SEK(kr)', name:'Swedish Krona'},
    {code:'SGD($)', name:'Singapore Dollar'},
    {code:'SHP(£)', name:'Saint Helena Pound'},
    {code:'SLL(SLL)', name:'Sierra Leonean Leone'},
    {code:'SOS(SOS)', name:'Somali Shilling'},
    {code:'SRD($)', name:'Surinamese Dollar'},
    {code:'SSP(£)', name:'South Sudanese Pound'},
    {code:'STN(STD)', name:'São Tomé and Príncipe Dobra'},
    {code:'SVC($)', name:'El Salvador Colon'},
    {code:'SYP(£)', name:'Syrian Pound'},
    {code:'SZL(SZL)', name:'Swazi Lilangeni'},
    {code:'THB(฿)', name:'Thai Baht'},
    {code:'TJS(SM)', name:'Tajikistani Somoni'},
    {code:'TMT(TMT)', name:'Turkmenistan Manat'},
    {code:'TND(د.ت)', name:'Tunisian Dinar'},
    {code:'TOP(T$)', name:'Tongan Paʻanga'},
    {code:'TRY(₺)', name:'Turkish Lira'},
    {code:'TTD(TT$)', name:'Trinidad and Tobago Dollar'},
    {code:'TVD($)', name:'Tuvaluan Dollar'},
    {code:'TWD($)', name:'New Taiwan Dollar'},
    {code:'TZS(TZS)', name:'Tanzanian Shilling'},
    {code:'UAH(₴)', name:'Ukrainian Hryvnia'},
    {code:'UGX(UGX)', name:'Ugandan Shilling'},
    {code:'USD($)', name:'United States Dollar'},
    {code:'UYU($U)', name:'Uruguayan Peso'},
    {code:'UZS(лв)', name:'Uzbekistani Soʻm'},
    {code:'VEF(Bs)', name:'Venezuelan Bolívar'},
    {code:'VND(₫)', name:'Vietnamese Dồng'},
    {code:'VUV(VUV)', name:'Vanuatu Vatu'},
    {code:'WST(SAT)', name:'Samoan Tālā'},
    {code:'XAF(FCFA)', name:'Central African CFA Franc'},
    {code:'XCD(EC$)', name:'Eastern Caribbean Dollar'},
    {code:'XOF(CFA)', name:'West African CFA Franc'},
    {code:'XPF(CFPF)', name:'CFP Franc'},
    {code:'YER(﷼)', name:'YEMEN RIAL'},
    {code:'ZAR(R)', name:'South African Rand'},
    {code:'ZMW(ZMW)', name:'Zambian Kwacha'},
    {code:'ZWB(Z$)', name:'Zimbabwean Dollar'},
];